import numpy as np
T=np.array([[0,0,0,.576],[0,0,1,.008],[0,1,0,.144],
            [0,1,1,.072],[1,0,0,.064],[1,0,1,.012],
            [1,1,0,.016],[1,1,1,.108]])
print(T)
print("-----------------------------")
print("Disapositiva 6")
print("Element en la fila 0, columna 3: T[0,3]")
print(T[0,3])
print("Element en la fila 0, última columna: T[0,-1]")
print(T[0,-1])
print("Element en la fila 0(inicial) a 3 de l' última columna: T[0:4,-1] ó T[:4,-1]")
print(T[0:4,-1])
print(T[:4,-1])
print("Element en la fila 4(inicial) a 7 de l' última columna: T[4:8,-1] ó T[4:,-1]")
print(T[4:8,-1])
print(T[4:,-1])
print("Elements (en totes les files) de l'ultima columna: T[:,-1]")
print(T[:,-1])
print("-----------------------------")
print(T)
print("Disapositiva 7")
print("Elements de les files 0,1,4,5 de l'ultima columna: T[[0,1,4,5],-1]")
print(T[[0,1,4,5],-1])
print("Suma dels elements de la ultima columna: np.sum(T[:,-1])")
print(np.sum(T[:,-1]))
print("Files amb elements de la columna 0 nuls ¡Torna tupla!: np.where(T[:,0]==0)[0]")
print(np.where(T[:,0]==0))
#Lo anterior torna una tupla, cal possar [0] per a que torne els valor nomes.
print(np.where(T[:,0]==0)[0])
print("Files amb elements no nuls en la columna 1: np.where(T[:,1]!=0)[0]")
print(np.where(T[:,1]!=0)[0])
print("Files amb elements nuls en les columnes 1 i 2: np.where((T[:,1]==0) & (T[:,2]==0))[0]")
print(np.where((T[:,1]==0) & (T[:,2]==0))[0])
print("Elements en ultima col. de files amb 0 en les cols. 1 i 2: T[np.where((T[:,1]==0) & (T[:,2]==0))[0],-1]")
print(T[np.where((T[:,1]==0) & (T[:,2]==0))[0],-1])
print("Suma d’elem. en ultima col. de files amb 1 en les cols. 1 i 2: np.sum(T[np.where((T[:,1]==1) & (T[:,2]==1))[0],-1])")
print(np.sum(T[np.where((T[:,1]==1) & (T[:,2]==1))[0],-1]))
print("-----------------------------")
print(T)
print("Disapositiva 9: Aplicacions de la regla de la suma i del producte.")
print("Probabilitat de caries i buit alhora. c=1 i h=1")
Pc1h1=np.sum(T[np.where((T[:,1]==1) & (T[:,2]==1))[0],-1])
print('Variable Pc1h1 = %.5f' %Pc1h1)
print("Probabilitat de buit. h=1")
Ph1=np.sum(T[np.where(T[:,2]==1)[0],-1])
print('Variable Ph1 = %.5f' %Ph1)
print("Probabilitat de caries despres de observar buit. P(c=1|h=1)")
Pc1Dh1=Pc1h1 / Ph1
print('Variable Pc1Dh1 = %.5f' %Pc1Dh1)
print("Probabilitat de dolor sabent que hi ha caries. P(d=1|c=1)")
Pc1d1=np.sum(T[np.where((T[:,1]==1) & (T[:,0]==1))[0],-1])
Pc1=np.sum(T[np.where(T[:,1]==1)[0],-1])
Pd1Dc1=Pc1d1 / Pc1
print('Variable Pd1Dc1 = %.5f' %Pd1Dc1)
print("-----------------------------")
print("Disapositiva 10:")
print("Probabilitat de caries sabes que hi ha dolor. P(c=1|d=1)")
Pd1=np.sum(T[np.where(T[:,0]==1)[0],-1])
Pc1Dd1=(Pc1)*(Pd1Dc1/Pd1)
print('Variable Pc1Dd1 = %.5f' %Pc1Dd1)
